# Generated by Django 4.1.1 on 2023-02-20 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Atractivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, verbose_name="nombre")),
                (
                    "calificacion",
                    models.CharField(max_length=50, verbose_name="calificacion"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "numero_unidad",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("patente", models.CharField(max_length=50, verbose_name="patente")),
                ("fecha_compra", models.DateField()),
                ("estado", models.CharField(max_length=50, verbose_name="Estado")),
            ],
        ),
        migrations.CreateModel(
            name="Chofer",
            fields=[
                (
                    "nro_documento",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("legajo", models.CharField(max_length=50, verbose_name="legajo")),
                ("nombre", models.CharField(max_length=50, verbose_name="nombre")),
                ("apellido", models.CharField(max_length=50, verbose_name="apellido")),
            ],
        ),
        migrations.CreateModel(
            name="DetalleCadaParada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado_parada",
                    models.CharField(max_length=50, verbose_name="estado_parada"),
                ),
                ("numero_orden", models.IntegerField(verbose_name="numero_orden")),
                ("conexion", models.IntegerField(verbose_name="conexion")),
            ],
        ),
        migrations.CreateModel(
            name="Parada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, verbose_name="nombre")),
                (
                    "descripcion",
                    models.CharField(max_length=100, verbose_name="descripcion"),
                ),
                (
                    "direccion",
                    models.CharField(max_length=50, verbose_name="direccion"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recorrido",
            fields=[
                (
                    "numero_recorrido",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("dia", models.DateField()),
                ("nombre", models.CharField(max_length=50, verbose_name="nombre")),
                ("hora_inicio", models.TimeField()),
                ("hora_finalizacion", models.TimeField()),
                ("duracion_aprox", models.TimeField()),
                ("frecuencia", models.TimeField()),
                ("color", models.CharField(max_length=50, verbose_name="color")),
                (
                    "lista_detalle_parada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="andino_turismo.detallecadaparada",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Viaje",
            fields=[
                ("nombre", models.CharField(max_length=50, verbose_name="nombre")),
                ("dia", models.DateField()),
                ("hora_inicio_prevista", models.TimeField()),
                ("hora_inicio", models.TimeField()),
                ("hora_fin", models.TimeField()),
                ("numero", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="andino_turismo.bus",
                    ),
                ),
                (
                    "chofer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="andino_turismo.chofer",
                    ),
                ),
                (
                    "recorrido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="andino_turismo.recorrido",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="detallecadaparada",
            name="parada",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="andino_turismo.parada"
            ),
        ),
    ]
